### ISSUE TITLE
I just want to say thank you

### ISSUE THREAD

**Issue by lsps9150414** [axelpale/nudged#28]
Working on gesture handling and this lib literally saved me tons of hours. Please accept my worship 🙇🏻‍♂️ 🙇🏻‍♂️ 🙇🏻‍♂️

**Comment by axelpale** [comment]
Worship accepted. Thank you, made my day! In case you are working on gesture handling with web browsers, you might be interested in an article I just published today on the subject: https://www.akselipalen.com/2022/05/24/design-of-gesture-recognition-libraries-for-web/

The article might have some rough edges to finish. All feedback is welcome.

**Comment by lsps9150414** [comment]
@axelpale thanks for the article it's very insightful. Btw do you have plans to make this repo Typescript friendly? Might be able to help with that when I'm done with my current project.

**Comment by axelpale** [comment]
I am glad you liked it. Hey, TypeScript type definitions are a good idea! I opened an issue for it. There is also a quick general question for you in case you could share a bit guiding insight on how we should approach the issue: https://github.com/axelpale/nudged/issues/29
